config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :users, controllers: { confirmations: 'confirmations' ,registrations: 'registrations'}

  devise_scope :user do
    authenticated :user do
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
      root 'plainpage#index', as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable



  has_paper_trail
  #TODO: Implement "accepts_nested_attributes_for:" method, and update registration form


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :prepare_unobtrusive_flash

  before_action :set_paper_trail_whodunnit
  @page_title=' '

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    root_path
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :country, :city, :details, :company, :likes, :visits)
    end
end

app/controllers/plainpage_controller.rb
class PlainpageController < ApplicationController
  before_action :authenticate_user!


  def index
    @page_title='Dashboard'
    flash[:success ] = "Success Flash Message: Welcome to GentellelaOnRails"
    #other alternatives are
    # flash[:warn ] = "Israel don't quite like warnings"
    #flash[:danger ] = "Naomi let the dog out!"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :likes %>
    <%= f.number_field :likes %>
  </div>

  <div class="field">
    <%= f.label :visits %>
    <%= f.number_field :visits %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Country</th>
      <th>City</th>
      <th>Details</th>
      <th>Company</th>
      <th>Likes</th>
      <th>Visits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody scope="row">
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.country %></td>
        <td><%= job.city %></td>
        <td><%= job.details %></td>
        <td><%= job.company %></td>
        <td><%= job.likes %></td>
        <td><%= job.visits %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Country:</strong>
  <%= @job.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @job.city %>
</p>

<p>
  <strong>Details:</strong>
  <%= @job.details %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @job.likes %>
</p>

<p>
  <strong>Visits:</strong>
  <%= @job.visits %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><%= content_for?(:title) ? yield(:title) : "Rails Jobs" %> </title>

  <meta name="description" content="RocketMD, Dashboard, Medical, Software " />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="RocketMD">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


</head>

<body >

<div class="app" id="app">
<%= render "partials/sidenav" %>


  <div id="content" class="app-content box-shadow-z0" role="main">
    <%= render "partials/topnav" %>
    <%= render "partials/footer" %>
    <div ui-view class="app-body" id="view">
    <div style="min-height: 200px">
      <%= yield %>
    </div>
    </div>

  </div>
  <%= render "partials/theme_switcher" %>
</div>



  <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rocket MD Software</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<div class="app" id="app">

  <div class="center-block w-xxl w-auto-xs p-y-md">
    <div class="navbar">
      <div class="pull-center">
        <div ui-include="'../views/blocks/navbar.brand.html'"></div>
      </div>
    </div>
    <div class="p-a-md box-color r box-shadow-z1 text-color m-a">

      <%= yield %>
    </div>

    <div class="p-v-lg text-center">
      <%= render "devise/shared/links" %>
    </div>
  </div>

</div>

</body>

app/views/partials/_footer.html.erb
<div class="app-footer">
  <div class="p-a text-xs">
    <div class="pull-right text-muted">
      &copy; Copyright <strong>Rocket MD</strong> <span class="hidden-xs-down">- Built with <i class="fa fa-heart" style="color: red"></i> v0.2</span>
      <a ui-scroll-to="content"><i class="fa fa-long-arrow-up p-x-sm"></i></a>
    </div>
    <div class="nav">
      <a class="nav-link" href="../">About</a>
      <span class="text-muted">-</span>
      <a class="nav-link label accent" href="https://github.com/Eduardoveras94/RocketMD">Github</a>
    </div>
  </div>
</div>

app/views/partials/_sidenav.html.erb
<div id="aside" class="app-aside modal fade nav-dropdown">
  <!-- fluid app aside -->
  <div class="left navside dark dk" layout="column">
    <div class="navbar no-radius">
      <!-- brand -->
      <a class="navbar-brand">
        <div ui-include="'../assets/images/logo.svg'"></div>
        <i class="fa fa-rocket fa-lg"></i>
        <span class="hidden-folded inline">Rocket MD</span>
      </a>
      <!-- / brand -->
    </div>
    <div flex class="hide-scroll">
      <nav class="scroll nav-light">

        <ul class="nav" ui-nav>
          <li class="nav-header hidden-folded">
            <small class="text-muted">Main</small>
          </li>

          <li>
            <%= link_to root_path do %>
                    <span class="nav-icon">
                      <i class="material-icons">&#xe3fc;
                        <span ui-include="'../assets/images/i_0.svg'"></span>
                      </i>
                    </span>
                <span class="nav-text">Dashboard</span>
            <% end %>
          </li>
          <li>
            <%= link_to jobs_path do %>
             <span class="nav-icon">
                      <i class="fa fa-wheelchair fa-lg">
                      </i>
                    </span>
                <span class="nav-text">Jobs</span>

            <% end %>
          </li>

          <li>
            <a>
                    <span class="nav-caret">
                      <i class="fa fa-caret-down"></i>
                    </span>
              <span class="nav-label">
                      <b class="label rounded label-sm primary">5</b>
                    </span>
              <span class="nav-icon">
                      <i class="material-icons">&#xe5c3;
                        <span ui-include="'../assets/images/i_1.svg'"></span>
                      </i>
                    </span>
              <span class="nav-text">Test Menu</span>
            </a>
            <ul class="nav-sub">
              <li>
                <a href="#">
                  <span class="nav-text">Inbox</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="nav-text">Contacts</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="nav-text">Calendar</span>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-header hidden-folded">
            <small class="text-muted">Help</small>
          </li>

          <li class="hidden-folded">
            <a href="https://github.com/Eduardoveras94/RocketMD/wiki">
              <span class="nav-text">Documentation</span>
            </a>
          </li>

        </ul>
      </nav>
    </div>
    <div flex-no-shrink class="b-t">
      <div class="nav-fold">
        <a href="profile.html">
        	    <span class="pull-left">
                <%= image_tag "gentelella/production/assets/images/a0.jpg", alt: "...", class: "w-40 img-circle" %>
        	    </span>
          <span class="clear hidden-folded p-x">
        	      <span class="block _500"><%= current_user.name %></span>
        	      <small class="block text-muted"><i class="fa fa-circle text-success m-r-sm"></i>online</small>
        	    </span>
        </a>
      </div>
    </div>
  </div>
</div>
<!-- / -->

app/views/partials/_theme_switcher.html.erb
<div id="switcher">
  <div class="switcher box-color dark-white text-color" id="sw-theme">
    <a href ui-toggle-class="active" target="#sw-theme" class="box-color dark-white text-color sw-btn">
      <i class="fa fa-gear"></i>
    </a>
    <div class="box-header">
      <a href="#" class="btn btn-xs rounded danger pull-right">BUY</a>
      <h2>Theme Switcher</h2>
    </div>
    <div class="box-divider"></div>
    <div class="box-body">
      <p class="hidden-md-down">
        <label class="md-check m-y-xs"  data-target="folded">
          <input type="checkbox">
          <i class="green"></i>
          <span class="hidden-folded">Folded Aside</span>
        </label>
        <label class="md-check m-y-xs" data-target="boxed">
          <input type="checkbox">
          <i class="green"></i>
          <span class="hidden-folded">Boxed Layout</span>
        </label>
        <label class="m-y-xs pointer" ui-fullscreen>
          <span class="fa fa-expand fa-fw m-r-xs"></span>
          <span>Fullscreen Mode</span>
        </label>
      </p>
      <p>Colors:</p>
      <p data-target="themeID">
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'primary', accent:'accent', warn:'warn'}">
          <input type="radio" name="color" value="1">
          <i class="primary"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'accent', accent:'cyan', warn:'warn'}">
          <input type="radio" name="color" value="2">
          <i class="accent"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'warn', accent:'light-blue', warn:'warning'}">
          <input type="radio" name="color" value="3">
          <i class="warn"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'success', accent:'teal', warn:'lime'}">
          <input type="radio" name="color" value="4">
          <i class="success"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'info', accent:'light-blue', warn:'success'}">
          <input type="radio" name="color" value="5">
          <i class="info"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'blue', accent:'indigo', warn:'primary'}">
          <input type="radio" name="color" value="6">
          <i class="blue"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'warning', accent:'grey-100', warn:'success'}">
          <input type="radio" name="color" value="7">
          <i class="warning"></i>
        </label>
        <label class="radio radio-inline m-a-0 ui-check ui-check-color ui-check-md" data-value="{primary:'danger', accent:'grey-100', warn:'grey-300'}">
          <input type="radio" name="color" value="8">
          <i class="danger"></i>
        </label>
      </p>
      <p>Themes:</p>
      <div data-target="bg" class="text-u-c text-center _600 clearfix">
        <label class="p-a col-xs-6 light pointer m-a-0">
          <input type="radio" name="theme" value="" hidden>
          Light
        </label>
        <label class="p-a col-xs-6 grey pointer m-a-0">
          <input type="radio" name="theme" value="grey" hidden>
          Grey
        </label>
        <label class="p-a col-xs-6 dark pointer m-a-0">
          <input type="radio" name="theme" value="dark" hidden>
          Dark
        </label>
        <label class="p-a col-xs-6 black pointer m-a-0">
          <input type="radio" name="theme" value="black" hidden>
          Black
        </label>
      </div>
    </div>
  </div>

  <div class="switcher box-color black lt" id="sw-demo">
    <a href ui-toggle-class="active" target="#sw-demo" class="box-color black lt text-color sw-btn">
      <i class="fa fa-list text-white"></i>
    </a>
    <div class="box-header">
      <h2>Demos</h2>
    </div>
    <div class="box-divider"></div>
    <div class="box-body">
      <div class="text-u-c text-center _600 clearfix">
        <a href="dashboard.html"
           class="p-a col-xs-6 primary">
          <span class="text-white">Default</span>
        </a>
        <a href="dashboard.0.html"
           class="p-a col-xs-6 success">
          <span class="text-white">Zero</span>
        </a>
        <a href="dashboard.1.html"
           class="p-a col-xs-6 blue">
          <span class="text-white">One</span>
        </a>
        <a href="dashboard.2.html"
           class="p-a col-xs-6 warn">
          <span class="text-white">Two</span>
        </a>
        <a href="dashboard.3.html"
           class="p-a col-xs-6 danger">
          <span class="text-white">Three</span>
        </a>
        <a href="dashboard.4.html"
           class="p-a col-xs-6 green">
          <span class="text-white">Four</span>
        </a>
        <a href="dashboard.5.html"
           class="p-a col-xs-6 info">
          <span class="text-white">Five</span>
        </a>
        <div
        class="p-a col-xs-6 lter">
          <span class="text">...</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_topnav.html.erb
<div class="app-header white box-shadow">
  <div class="navbar">
    <!-- Open side - Naviation on mobile -->
    <a data-toggle="modal" data-target="#aside" class="navbar-item pull-left hidden-lg-up">
      <i class="material-icons">&#xe5d2;</i>
    </a>
    <!-- / -->

    <!-- Page title - Bind to $state's title -->
    <div class="navbar-item pull-left h5" ng-bind="$state.current.data.title" id="pageTitle"></div>

    <!-- navbar right -->
    <ul class="nav navbar-nav pull-right">
      <li class="nav-item dropdown pos-stc-xs">
        <a class="nav-link" href data-toggle="dropdown">
          <i class="material-icons">&#xe7f5;</i>
          <span class="label label-sm up warn">3</span>
        </a>
        <div class="dropdown-menu pull-right w-xl animated fadeInUp no-bg no-border no-shadow">
          <div class="scrollable" style="max-height: 220px">
            <ul class="list-group list-group-gap m-a-0">
              <li class="list-group-item black lt box-shadow-z0 b">
          <span class="pull-left m-r">
            <img src="../assets/images/a0.jpg" alt="..." class="w-40 img-circle">
          </span>
                <span class="clear block">
            Use awesome <a href class="text-primary">animate.css</a><br>
            <small class="text-muted">10 minutes ago</small>
          </span>
              </li>
              <li class="list-group-item black lt box-shadow-z0 b">
          <span class="pull-left m-r">
            <img src="../assets/images/a1.jpg" alt="..." class="w-40 img-circle">
          </span>
                <span class="clear block">
            <a href class="text-primary">Joe</a> Added you as friend<br>
            <small class="text-muted">2 hours ago</small>
          </span>
              </li>
              <li class="list-group-item dark-white text-color box-shadow-z0 b">
          <span class="pull-left m-r">
            <img src="../assets/images/a2.jpg" alt="..." class="w-40 img-circle">
          </span>
                <span class="clear block">
            <a href class="text-primary">Danie</a> sent you a message<br>
            <small class="text-muted">1 day ago</small>
          </span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link clear" href data-toggle="dropdown">
                  <span class="avatar w-32">
                    <%= image_tag "gentelella/production/assets/images/a0.jpg" , alt: "..." %>
                    <i class="on b-white bottom"></i>
                  </span>
        </a>
        <div class="dropdown-menu pull-right dropdown-menu-scale">

          <a class="dropdown-item" href="#">
            <span>Profile</span>
          </a>
          <a class="dropdown-item" href="<%= rails_admin_path %>">
            <span>Admin Settings</span>
            <span class="label primary m-l-xs">3/9</span>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="https://github.com/Eduardoveras94/RocketMD">
            Need help?
          </a>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "dropdown-item") %>
        </div>

      </li>
      <li class="nav-item hidden-md-up">
        <a class="nav-link" data-toggle="collapse" data-target="#collapse">
          <i class="material-icons">&#xe5d4;</i>
        </a>
      </li>
    </ul>
    <!-- / navbar right -->

    <!-- navbar collapse -->
    <div class="collapse navbar-toggleable-sm" id="collapse">
      <!-- search form -->
      <form class="navbar-form form-inline pull-right pull-none-sm navbar-item v-m" role="search">
        <div class="form-group l-h m-a-0">
          <div class="input-group">
            <input type="text" class="form-control form-control-sm p-x b-a rounded" placeholder="Search projects...">
          </div>
        </div>
      </form>
      <!-- / search form -->

      <!-- link and dropdown -->
      <ul class="nav navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link" href data-toggle="dropdown">
            <i class="fa fa-fw fa-plus text-muted"></i>
            <span>New</span>
          </a>
          <div class="dropdown-menu dropdown-menu-scale">
            <a class="dropdown-item" ui-sref="app.inbox.compose">
              <span>Inbox</span>
            </a>
            <a class="dropdown-item" ui-sref="app.todo">
              <span>Todo</span>
            </a>
            <a class="dropdown-item" ui-sref="app.note.list">
              <span>Note</span>
              <span class="label primary m-l-xs">3</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" ui-sref="app.contact">Contact</a>
          </div>

        </li>
      </ul>
      <!-- / -->
    </div>
    <!-- / navbar collapse -->
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>